In [1]:
import numpy as np

In [7]:
np.zeros((2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
np.ones((5, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
np.random.seed(10)
np.random.random((10, 10))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
        0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
        0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
        0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895],
       [0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
        0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 , 0.35165264,
        0.75464769, 0.29596171, 0.88393648, 0.32551164, 0.1650159 ],
       [0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445,
        0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413],
       [0.59737165, 0.90283176, 0.53455795, 0.59020136, 0.03928177,
        0.35718176, 0.07961309, 0.30545992, 0.33071931, 0.7738303 ],
       [0.03995921, 0.42949218, 0.3149268

In [40]:
np.random.seed(15)
np.random.randint(10, 20, size=(2, 4))

array([[18, 15, 15, 17],
       [10, 17, 15, 16]])

In [44]:
np.random.uniform(size=(3, 5))

array([[0.32976593, 0.19542482, 0.68404621, 0.35109886, 0.77103611],
       [0.7917995 , 0.44387459, 0.2688283 , 0.02390442, 0.37133257],
       [0.09773088, 0.72752255, 0.45944443, 0.52049647, 0.68456904]])

In [52]:
np.random.uniform(10.0, 50.0, size=(3, 5))

array([[14.06573728, 19.95859685, 48.66449269, 42.87386022, 27.40464523],
       [43.11249344, 11.90147959, 40.79412975, 48.62406252, 11.23492538],
       [33.63584049, 39.93343309, 17.93722162, 28.09064087, 20.11076108]])

In [55]:
np.random.seed(10)
np.random.choice(np.array([1, 2, 3]), size=10)

array([2, 2, 1, 1, 2, 1, 2, 2, 1, 2])